# Run with:
# docker compose -f examples/calvin/compose.yml up --build
services:
  runtime:
    image: calvin
    depends_on:
      - openpi_server
    build:
      context: ../..
      dockerfile: examples/calvin/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - $PWD:/app
      - ../../data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  openpi_server:
    image: openpi_server
    build:
      context: ../..
      dockerfile: scripts/serve_policy.Dockerfile
    init: true
    tty: true
    network_mode: host
    volumes:
      - $PWD:/app
    environment:
      - SERVER_ARGS

    # Comment out this block if not running on a machine with GPUs.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
